### ISSUE TITLE
Добавить назначение администраторов и дать возможность выбирать типы пользователей: 

### ISSUE THREAD

**Issue by kushedow** [kushedow/imperia#15]
![image](https://user-images.githubusercontent.com/7995387/29486691-e2623e10-84f4-11e7-89fe-91c91db82253.png)

- [ ] Ученик
- [ ] Преподаватель
- [ ] Администратор
- [ ] Приглашающий

**Comment by nismangulov** [comment]
@kushedow это готово? можно закрывать?
