### ISSUE TITLE
При тестировании в партнерке добавить отметку «Если не знаете ответ»

### ISSUE THREAD

**Issue by kushedow** [kushedow/imperia#23]
![image](https://user-images.githubusercontent.com/7995387/29488434-833bc248-8513-11e7-8db5-48e8b5c69803.png)

Текст: Если вы не знаете ответ, поставьте прочерк в поле(полях) для ответа

**Comment by nismangulov** [comment]
@kushedow Глеб, где мы сможем увидеть верстку?

**Comment by kushedow** [comment]
Просто добавить текст после кнопки. Верстки нет. Можно криво добавить

**Comment by nismangulov** [comment]
Посмотрел - оказывается уже текст есть https://i.imgur.com/eSXoPvx.png
