### ISSUE TITLE
Реализовать простую логику тестирования 

### ISSUE THREAD

**Issue by kushedow** [kushedow/imperia#6]
При запуске теста прверяктся есть ли у клиента заявка на этот предмет. 

Если нет - открывается вопрос с первым порядковым номером.  

В страницу подгружается контент вопроса и его код проверки обернутый в функцию. 

После каких то действий пользователя он нажимает кнопку зеленого цвета под формой .  Тогда код выполняется, а результат записывается в поле которое отправляется на сервер.  

Если заявка есть, то в поле test сохранен json – список объектовв формате

 id вопроса - ответ - кол-во баллов

Каждый раз при вызове страницы теста мы показываем тот вопрос на который ещё нет записи об ответе, после ответа - записываем его

**Comment by nismangulov** [comment]
@kushedow это готово? можно закрывать?
